-- PostgreSQL Schema for Envelope Budgeting App
-- Note: Aurora DSQL does not support sequences, foreign keys, or GENERATED ALWAYS AS IDENTITY
-- IDs must be generated by application code (e.g., UUIDs or app-managed counters)

-- User table: stores user account information and preferences
CREATE TABLE users(
    id VARCHAR(36) PRIMARY KEY,
    cognito_sub VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    interval_type VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    interval_start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    plaid_access_token TEXT,
    plaid_item_id VARCHAR(255),
    plaid_cursor VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Envelope table: stores budget envelopes for each user
CREATE TABLE envelopes(
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    amount_type VARCHAR(20) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    refresh_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- EnvelopeRule table: defines automatic categorization rules
CREATE TABLE envelope_rules(
    id VARCHAR(36) PRIMARY KEY,
    envelope_id VARCHAR(36) NOT NULL,
    plaid_category VARCHAR(255),
    merchant_pattern VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(envelope_id, plaid_category, merchant_pattern)
);

-- Transaction table: stores all financial transactions from Plaid
CREATE TABLE transactions(
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    envelope_id VARCHAR(36),
    plaid_transaction_id VARCHAR(255) UNIQUE,
    datetime TIMESTAMP NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    type VARCHAR(10) NOT NULL,
    description TEXT,
    merchant_name VARCHAR(255),
    plaid_category VARCHAR(255),
    is_categorized BOOLEAN NOT NULL DEFAULT FALSE,
    categorization_source VARCHAR(10),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Notification table: stores notification preferences for envelopes (not implemented in MVP)
CREATE TABLE notifications(
    id VARCHAR(36) PRIMARY KEY,
    envelope_id VARCHAR(36) NOT NULL,
    threshold_type VARCHAR(20) NOT NULL,
    threshold_value DECIMAL(10, 2) NOT NULL,
    notification_type VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for query optimization (ASYNC required by Aurora DSQL)
CREATE INDEX ASYNC idx_transactions_user_id ON transactions(user_id);
CREATE INDEX ASYNC idx_transactions_envelope_id ON transactions(envelope_id);
CREATE INDEX ASYNC idx_transactions_datetime ON transactions(datetime);
CREATE INDEX ASYNC idx_transactions_is_categorized ON transactions(is_categorized);
CREATE INDEX ASYNC idx_envelopes_user_id ON envelopes(user_id);
CREATE INDEX ASYNC idx_envelope_rules_envelope_id ON envelope_rules(envelope_id);
CREATE INDEX ASYNC idx_notifications_envelope_id ON notifications(envelope_id);
